# Generated by Django 4.1.6 on 2023-03-29 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=100)),
                ('bookAuthor', models.CharField(max_length=35)),
                ('bookDiscp', models.TextField(max_length=350)),
                ('bookEdition', models.IntegerField()),
                ('bookLang', models.CharField(max_length=35)),
                ('bookCategory', models.CharField(max_length=35)),
                ('bookQuantity', models.IntegerField()),
                ('bookImage', models.ImageField(blank=True, upload_to='')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('dept', models.CharField(max_length=35)),
                ('isActive', models.BooleanField(default=True)),
                ('mobile', models.IntegerField()),
                ('admissionDate', models.DateField()),
                ('dob', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqType', models.CharField(max_length=35)),
                ('reqDesc', models.CharField(max_length=100)),
                ('reqDate', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=100)),
                ('salary', models.FloatField()),
                ('isActive', models.BooleanField(default=True)),
                ('mobile', models.IntegerField()),
                ('joiningDate', models.DateField()),
                ('dob', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('returnDate', models.DateField(default='')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
