# Generated by Django 4.1.6 on 2023-03-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='limit',
            field=models.IntegerField(default=4),
        ),
    ]
