# Generated by Django 4.1.6 on 2023-03-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fine',
            field=models.FloatField(default=0),
        ),
    ]
