# Generated by Django 4.1.6 on 2023-03-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
