# Generated by Django 4.1.6 on 2023-03-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_otp_email_alter_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
