# Generated by Django 4.1.6 on 2023-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
